### ISSUE TITLE
Implement SSL (https)

### ISSUE THREAD

**Issue by hunterjsb** [hunterjsb/LoLPlayerScraper#3]

**Comment by johncameronthomas** [comment]
Options to fix port issue:
1. AT&T lets us do it (unlikely)
2. Change ISP
3. Digital Ocean linux box

**Comment by chandlerxn** [comment]
Option 1 was the resolution.  Configured nginx with a new SSL cert and SSL is now allowing a remote connection to https://xannation.com.

The current issue is that the page goes to an nginx 502 error page instead of going through to gunicorn.
